const reverseBrainstorming =  `/images/events/reverseBrainstorming.webp`
const codeProblem =  `/images/events/codeproblem.webp`
const AIML=  `/images/events/AIML.webp`
const chemInnovation=  `/images/events/chemInnovation.webp`
const aspen =  `/images/events/aspen.webp`
const chemQuiz=  `/images/events/chemQuiz.webp`
const chemEngage=  `/images/events/chemEngage.webp`
const chemMeme=  `/images/events/chemMeme.webp`
const photography =  `/images/events/photography.webp`
const quiz=  `/images/events/quiz.webp`
const code=  `/images/events/code.webp`
const ML=  `/images/events/ML.webp`
const caseStudy =  `/images/events/case.webp`
const debate=  `/images/events/debate.webp`
const meme=  `/images/events/meme.webp`
const brainstorming =  `/images/events/brainstorming.webp`
const aspen1=  `/images/events/download.webp`



const eventDetails=[
  {
    title:"REVERSE BRAINSTORMING",
    description1:`ARE YOU TIRED OF THE SAME OLD BRAINSTORMING TECHNIQUES? WANT TO TRY SOMETHING NEW AND INNOVATIVE?`,
    description2:"THEN JOIN US AT FUGACITY FEST FOR OUR REVERSE BRAINSTORMING COMPETITION!,",
    description3:"HOSTED BY THE CHEMICAL ENGINEERING ASSOCIATION, THIS COMPETITION CHALLENGES PARTICIPANTS TO THINK OUTSIDE THE BOX BY IDENTIFYING AND REVERSING THE PROBLEMS ASSOCIATED WITH A GIVEN TOPIC. IT'S A GREAT OPPORTUNITY TO SHARPEN YOUR CRITICAL THINKING AND PROBLEM-SOLVING SKILLS.",
    description4:"SO GATHER YOUR FRIENDS AND REGISTER FOR THE COMPETITION NOW! WE CAN'T WAIT TO SEE YOUR CREATIVE IDEAS AND INNOVATIVE SOLUTIONS.",
    url1:reverseBrainstorming,
    url2:brainstorming
  },
  {
    title:"CODE THE PROBLEM",
    description1:`ATTENTION ALL CODERS AND PROBLEM-SOLVERS! THE CHEMICAL ENGINEERING ASSOCIATION IS THRILLED TO ANNOUNCE "CODE THE PROBLEM," AN EXCITING EVENT THAT WILL TAKE PLACE DURING OUR ANNUAL FEST, FUGACITY.`,
    description2:`ARE YOU READY TO PUT YOUR CODING SKILLS AND PROBLEM-SOLVING ABILITIES TO THE TEST? "CODE THE PROBLEM" IS THE PERFECT OPPORTUNITY TO CONNECT WITH OTHER CODING ENTHUSIASTS, REGARDLESS OF YOUR EXPERIENCE LEVEL. THIS EVENT WILL CHALLENGE YOU TO THINK OUTSIDE THE BOX AND COME UP WITH INNOVATIVE SOLUTIONS TO COMPLEX PROBLEMS.`,
    description3:`REGISTRATION FOR "CODE THE PROBLEM" IS NOW OPEN! JOIN US AND COMPETE AGAINST SOME OF THE BEST CODERS IN THE INDUSTRY. YOU'LL HAVE A CHANCE TO SHOWCASE YOUR SKILLS, MEET OTHER TALENTED INDIVIDUALS, AND PUSH YOURSELF TO THE LIMIT.`,
    description4:`TEAM SIZE: MAXIMUM 3 MEMBERS IN EACH TEAM`,
    description5:`DON'T MISS OUT ON THIS INCREDIBLE OPPORTUNITY! MARK YOUR CALENDARS FOR FUGACITY AND REGISTER NOW FOR "CODE THE PROBLEM." STAY TUNED FOR MORE INFORMATION ABOUT THE EVENT AND ADDITIONAL DETAILS ABOUT THE COMPETITION. LET'S SEE WHO CAN CRACK THE CODE AND EMERGE AS THE CHAMPION!`,
    url1:codeProblem,
    url2:code
  },
  {
    title:"APPLICATION OF ML IN CHEMICAL ENGINEERING",
    description1:`ATTENTION CHEMICAL ENGINEERS!`,
    description2:"DO YOU WANT TO EXPLORE THE INTERSECTION OF CHEMICAL ENGINEERING AND MACHINE LEARNING? JOIN US FOR THE 'APPLICATION OF ML IN CHEMICAL ENGINEERING' EVENT, ORGANIZED BY THE CHEMICAL ENGINEERING ASSOCIATION AT FUGACITY FEST.",
    description3:"THIS EVENT IS AN EXCELLENT OPPORTUNITY FOR CHEMICAL ENGINEERS TO LEARN ABOUT THE LATEST DEVELOPMENTS AND PRACTICAL APPLICATIONS OF MACHINE LEARNING IN THE FIELD OF CHEMICAL ENGINEERING. THROUGH THIS EVENT, PARTICIPANTS WILL BE ABLE TO INTERACT WITH EXPERTS IN THE FIELD, SHARE THEIR EXPERIENCES, AND GAIN VALUABLE INSIGHTS ON HOW TO APPLY ML TECHNIQUES TO SOLVE REAL-WORLD PROBLEMS.",
    description4:"AS THE CHEMICAL INDUSTRY CONTINUES TO ADOPT ADVANCED TECHNOLOGIES, IT IS ESSENTIAL FOR CHEMICAL ENGINEERS TO KEEP UP WITH THE LATEST DEVELOPMENTS IN THEIR FIELD. THIS EVENT PROVIDES AN EXCELLENT OPPORTUNITY FOR PROFESSIONALS TO STAY AHEAD OF THE CURVE AND GAIN A COMPETITIVE EDGE IN THEIR CAREERS.",
    description5:"DON'T MISS OUT ON THIS CHANCE TO ENHANCE YOUR KNOWLEDGE, NETWORK WITH OTHER PROFESSIONALS, AND EXPLORE THE EXCITING WORLD OF ML IN CHEMICAL ENGINEERING. REGISTER NOW AND BE A PART OF THIS EXCITING EVENT!",
    url1:AIML,
    url2:ML
  },
  {
    title:"CASE STUDY CHALLENGE",
    description1:`ATTENTION CHEMICAL ENGINEERS!`,
    description2:"ARE YOU LOOKING TO ENHANCE YOUR PROBLEM-SOLVING SKILLS AND SHOWCASE YOUR INNOVATIVE IDEAS IN THE FIELD OF CHEMICAL ENGINEERING? JOIN US FOR THE CHEMICAL INNOVATION CASE STUDY, ORGANIZED BY THE CHEMICAL ENGINEERING ASSOCIATION AT FUGACITY FEST.",
    description3:"CASE STUDIES ARE AN EXCELLENT WAY TO APPLY THEORETICAL KNOWLEDGE TO REAL-WORLD SCENARIOS, AND THIS EVENT PROVIDES THE PERFECT PLATFORM FOR CHEMICAL ENGINEERS TO DO JUST THAT. THROUGH THIS CASE STUDY, PARTICIPANTS WILL BE ABLE TO EXPLORE DIFFERENT APPROACHES TO SOLVING COMPLEX PROBLEMS, LEARN FROM OTHER PROFESSIONALS' EXPERIENCES AND EXPAND THEIR KNOWLEDGE OF THE INDUSTRY.",
    description4:"MOREOVER, THIS EVENT IS AN EXCELLENT OPPORTUNITY TO NETWORK AND CONNECT WITH OTHER PROFESSIONALS IN THE FIELD, WHICH CAN LEAD TO NEW JOB OPPORTUNITIES, COLLABORATIONS AND PARTNERSHIPS.",
    description5:"DON'T MISS OUT ON THIS CHANCE TO ENHANCE YOUR SKILLS, SHOWCASE YOUR TALENTS AND MEET FELLOW PROFESSIONALS. REGISTER NOW AND BE A PART OF THIS EXCITING EVENT!",

    url1:chemInnovation,
    url2:caseStudy
  },
  {
    title:"ASPEN PLUS WORKSHOP",
    description1:`ATTENTION ALL CHEMICAL ENGINEERS AND PROCESS DESIGNERS!`,
    description2:"WE ARE EXCITED TO ANNOUNCE OUR UPCOMING ASPEN PLUS WORKSHOP, WHERE YOU WILL LEARN THE INS AND OUTS OF THIS POWERFUL PROCESS SIMULATION SOFTWARE.",
    description3:"WHETHER YOU ARE A BEGINNER OR HAVE PRIOR EXPERIENCE WITH ASPEN PLUS, THIS WORKSHOP IS PERFECT FOR YOU. OUR EXPERT INSTRUCTORS WILL GUIDE YOU THROUGH THE SOFTWARE, SHOWING YOU HOW TO BUILD PROCESS MODELS, SIMULATE VARIOUS SCENARIOS, AND ANALYSE THE RESULTS.",
    description4:"JOIN US ON 11TH MARCH AT 2 PM TO EXPAND YOUR KNOWLEDGE AND SKILLS IN PROCESS SIMULATION.LIMITED SPOTS AVAILABLE, SO SIGN UP NOW AT",
    description5:"DON'T MISS OUT ON THIS OPPORTUNITY TO ENHANCE YOUR EXPERTISE IN ASPEN PLUS!",
    url1:aspen,
    url2:aspen1
  },
  {
    title:"QUIZ",
    description1:`ALL CHEMICAL ENGINEERS AND PROCESS DESIGNERS, TAKE NOTE!.`,
    description2:"WE ARE PLEASED TO ANNOUNCE OUR FORTHCOMING ASPEN PLUS SESSION, WHERE YOU WILL LEARN MORE ABOUT THIS SOPHISTICATED PROCESS MODELLING SOFTWARE.",
    description3:"THIS SESSION IS IDEAL WHETHER YOU ARE A NOVICE OR HAVE PRIOR EXPERIENCE WITH ASPEN PLUS. OUR SKILLED EDUCATORS WILL WALK YOU THROUGH THE PROGRAMME, DEMONSTRATING HOW TO CREATE PROCESS MODELS, SIMULATE DIFFERENT SITUATIONS, AND ANALYSE THE OUTCOMES",
    description4:"REGISTER NOW TO DEVELOP YOUR PROCESS SIMULATION KNOWLEDGE AND ABILITIES.",
    description5:"THERE ARE JUST A FEW SEATS LEFT, SO JOIN UP TODAY AT DON'T PASS UP THIS CHANCE TO IMPROVE YOUR ASPEN PLUS KNOWLEDGE!",

    url1:chemQuiz,
    url2:quiz
  },
  {
    title:"DEBATE",
    description1:`ATTENTION ALL CHEMICAL ENGINEERING STUDENTS AND ENTHUSIASTS!`,
    description2:"THE CHEMICAL ENGINEERING ASSOCIATION IS EXCITED TO PRESENT THE UPCOMING CHEM ENGAGE (DEBATE) EVENT, AS PART OF THIS YEAR'S FUGACITY FEST",
    description3:"JOIN US ON FOR A STIMULATING DEBATE FEATURING SOME OF THE HOTTEST TOPICS AND CURRENT ISSUES IN THE FIELD OF CHEMICAL ENGINEERING. THIS IS YOUR CHANCE TO PARTICIPATE IN A LIVELY DISCUSSION AND SHOWCASE YOUR ANALYTICAL AND PERSUASIVE SKILLS.",
    description4:"THE CHEM ENGAGE (DEBATE) EVENT WILL FEATURE A RANGE OF TOPICS RELATED TO CHEMICAL ENGINEERING, INCLUDING SUSTAINABILITY, ENERGY, ENVIRONMENTAL IMPACT, AND MORE. OUR EXPERT PANEL OF JUDGES WILL PROVIDE FEEDBACK AND INSIGHTS, WHILE YOU GET TO ENGAGE IN THOUGHT-PROVOKING CONVERSATIONS WITH YOUR PEERS, LEARN FROM DIVERSE PERSPECTIVES AND OPINIONS, AND DEVELOP YOUR PUBLIC SPEAKING AND CRITICAL THINKING ABILITIES.",
    description5:"THIS IS THE PERFECT OPPORTUNITY TO NETWORK WITH INDUSTRY PROFESSIONALS AND CONNECT WITH FELLOW STUDENTS WHO SHARE YOUR PASSION FOR CHEMICAL ENGINEERING. DON'T MISS OUT ON THIS INCREDIBLE OPPORTUNITY TO BROADEN YOUR HORIZONS, EXPAND YOUR KNOWLEDGE, AND HAVE FUN WHILE DOING IT!",
    url1:chemEngage,
    url2:debate
  },
  {
    title:"CHEMICAL MEME CHALLENGE",
    description1:`ATTENTION ALL CHEMICAL ENGINEERING ENTHUSIASTS AND MEME-MAKERS!`,
    description2:"THE CHEMICAL ENGINEERING ASSOCIATION IS EXCITED TO PRESENT THE CHEMICAL MEME CHALLENGE, AN EVENT THAT CELEBRATES THE INTERSECTION OF CREATIVITY AND CHEMICAL ENGINEERING!",
    description3:"WE WANT TO SEE YOUR BEST CHEMICAL ENGINEERING MEMES THAT WILL MAKE US LAUGH, THINK, AND APPRECIATE THE AMAZING FIELD WE ARE ALL PASSIONATE ABOUT. THIS EVENT IS NOT ONLY A CHANCE TO SHOWCASE YOUR CREATIVITY AND HUMOUR, BUT ALSO A WAY TO CONNECT WITH LIKE-MINDED INDIVIDUALS IN THE CHEMICAL ENGINEERING COMMUNITY. SO JOIN US FOR A NIGHT OF LAUGHS AND BONDING AS WE CELEBRATE OUR LOVE FOR ALL THINGS CHEMICAL AND ENGINEERING.",
    description4:"DON'T FORGET TO BRING YOUR A-GAME AND YOUR BEST MEMES, AS WE'LL BE AWARDING PRIZES FOR THE TOP SUBMISSIONS. AND EVEN IF YOU'RE NOT PARTICIPATING, BE SURE TO FOLLOW THE HASHTAG AND SUPPORT YOUR FELLOW CHEMICAL ENGINEERING MEME-MAKERS.",
    description5:"SO MARK YOUR CALENDARS AND GET READY TO SHOW US WHAT YOU'VE GOT AT THE CHEMICAL MEME CHALLENGE, BROUGHT TO YOU BY THE CHEMICAL ENGINEERING ASSOCIATION!",
    url1:chemMeme,
    url2:meme
  },
  {
    title:"PHOTOGRAPHY CHALLENGE",
    description1:"ARE YOU A PHOTOGRAPHY ENTHUSIAST WITH A PASSION FOR CHEMISTRY? THE CHEMICAL ENGINEERING ASSOCIATION INVITES YOU TO PARTICIPATE IN OUR UPCOMING 'CHEMICAL PHOTOGRAPHY CHALLENGE' AT OUR ANNUAL FEST, FUGACITY.",
    description2:"THIS CHALLENGE IS OPEN TO ANYONE WHO ENJOYS CAPTURING THE BEAUTY OF CHEMICAL ELEMENTS AND REACTIONS THROUGH PHOTOGRAPHY. WHETHER YOU'RE A BEGINNER OR AN EXPERIENCED PHOTOGRAPHER, WE WANT YOU TO SHOWCASE YOUR CREATIVITY AND TALENT.",
    description3:"JOIN US FOR THE 'CHEMICAL PHOTOGRAPHY CHALLENGE' AND COMPETE AGAINST OTHER TALENTED PHOTOGRAPHERS. YOU'LL HAVE A CHANCE TO CONNECT WITH OTHER PHOTOGRAPHY ENTHUSIASTS AND SHOWCASE YOUR SKILLS TO A PANEL OF JUDGES.",
    description4:"THEME:CHEMICAL ENGINEERING",
    description5:"SO, MARK YOUR CALENDARS FOR FUGACITY AND GET READY TO PARTICIPATE IN THE 'CHEMICAL PHOTOGRAPHY CHALLENGE'! STAY TUNED FOR MORE INFORMATION ABOUT THE CHALLENGE AND HOW TO REGISTER. LET'S CAPTURE THE BEAUTY OF CHEMISTRY TOGETHER!",
    url1:photography,
    url2:photography
  },
]
export default eventDetails;